# Use an official Python runtime
FROM python:3.9

WORKDIR /app

# Copy the app folder into the container
COPY app /app

# Install Flask
RUN pip install flask

# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

# Expose port 5000
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]